AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an EC2 Instance with Parameters, Mappings, and Outputs for the Singapore region.

Parameters:
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: task
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

Mappings:
  AWSRegionToAMI:
    ap-southeast-1:
      AMI: ami-060e277c0d4cce553

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", AMI]
      SecurityGroups:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: "Allow SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: "Instance ID of the newly created EC2 instance"
    Value: !Ref MyEC2Instance

  AvailabilityZone:
    Description: "Availability Zone of the newly created EC2 instance"
    Value: !GetAtt MyEC2Instance.AvailabilityZone

  PublicDnsName:
    Description: "Public DNS name of the newly created EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicDnsName

  PublicIp:
    Description: "Public IP address of the newly created EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp
