AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an EC2 Instance, Elastic IP, Security Group, and output Public and Private IPs.

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium]
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC ID where the instance will be launched.

  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select the Subnet ID where the instance will be launched.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref Subnet
      ImageId: ami-060e277c0d4cce553
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref EC2Instance

Outputs:
  ElasticIPAddress:
    Description: The Elastic IP address associated with the EC2 instance
    Value: !Ref ElasticIP
    Export:
      Name: EC2ElasticIP

  PrivateIP:
    Description: The private IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: EC2PrivateIP
