AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an EC2 Instance, Elastic IP, Security Group, EBS volume, and output Public and Private IPs.

Resources:
  # Create a Security Group
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: "Allow SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # Create an EC2 Instance
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      KeyName: task
      SecurityGroupIds:
        - !Ref MySecurityGroup
      ImageId: ami-060e277c0d4cce553 
      BlockDeviceMappings:
        - DeviceName: /dev/sdh
          Ebs:
            VolumeSize: 8  # EBS volume size in GB

  # Create an Elastic IP
  MyElasticIP:
    Type: "AWS::EC2::EIP"

  # Associate Elastic IP with EC2 Instance
  MyEIPAssociation:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      InstanceId: !Ref MyEC2Instance
      EIP: !Ref MyElasticIP

Outputs:
  PublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !Ref MyElasticIP

  PrivateIP:
    Description: "Private IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PrivateIp
